i-rock/config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "test.host"
  devise_for :users
  resources :achievements do
    resources :encouragements, only: [ :new, :create ]
  end

  namespace :api do
    resources :achievements, only: [:index]
  end

  root to: 'welcome#index'
end

i-rock/app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  has_many :encouragements

  validates :title, presence: true
  validates :user, presence: true
  # validates :title, uniqueness: true

  validates :title, uniqueness: {
    scope: :user_id,
    message: "You can't have two achievements with the same title"
  }

  enum privacy: %I[public_access private_access friends_access]
  
  mount_uploader :cover_image, CoverImageUploader

  def description_html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end

  def silly_title
    "#{title} by #{user.email}"
  end

  def self.by_letter(letter)
    includes(:user).where('title LIKE ?', "#{letter}%").order("users.email")
  end

  private

  def unique_title_for_one_user
    existing_achievement = Achievement.find_by(title: title)
    if existing_achievement && existing_achievement.user == user
      errors.add(:title, "you can't have two achievements with the same title")
    end
  end
end

i-rock/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

i-rock/app/models/encouragement.rb
class Encouragement < ApplicationRecord
  belongs_to :user
  belongs_to :achievement

  validates :message, presence:true
end

i-rock/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :encouragements
end

i-rock/app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :owners_only, only: [:edit, :update, :destroy]

  def index
    @achievements = Achievement.public_access
  end

  def new
    @achievement = Achievement.new
  end

  def show
    @achievement = Achievement.find(params[:id])
  end

  def create
    @achievement = Achievement.new(achievement_params)
		@achievement.user = current_user
    if @achievement.save
      UserMailer.achievement_created(current_user.email, @achievement.id).deliver_now
      tweet = TwitterService.new.tweet(@achievement.title)
      redirect_to achievement_url(@achievement), notice: "Achievement has been created. We tweeted for you! #{tweet.url}"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @achievement.update_attributes(achievement_params)
      redirect_to achievement_path(@achievement)
    else
      render :edit
    end
  end

  def destroy
    Achievement.destroy(params[:id])
    redirect_to achievements_path
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :features)
  end

  def owners_only
    @achievement = Achievement.find(params[:id])
    if current_user != @achievement.user
      redirect_to achievements_path
    end
  end
end

i-rock/app/controllers/api/achievements_controller.rb
class Api::AchievementsController < ApiController
  def index
    @achievements = Achievement.public_access
  end
end

i-rock/app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :validate_header

  private

  def validate_header
    if request.headers['CONTENT_TYPE'] != 'application/json'
      render :index, status:400
    end
  end

end

i-rock/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

i-rock/app/controllers/encouragements_controller.rb
class EncouragementsController < ApplicationController
  before_action :authenticate_user
  before_action :authors_are_not_allowed
  before_action :only_one_encouragement

  def new
    @encouragement = Encouragement.new
  end

  def create
    @encouragement = Encouragement.new(encouragement_params.merge(
      user: current_user,
      achievement: @achievement
    ))

    @encouragement.save
    redirect_to achievement_path(@achievement), notice: 'Thank you for encouragement!'
  end

  private

  def encouragement_params
    params.require(:encouragement).permit(:message) 
  end

  def authenticate_user
    @achievement = Achievement.find(params[:achievement_id])

    unless current_user
      redirect_to achievement_path(@achievement), alert: 'You must be logged in to encourage people'
      return
    end
  end

  def authors_are_not_allowed
    if current_user.id == @achievement.user_id
      redirect_to achievement_path(@achievement), alert: "You can't encourage yourself"
      return
    end
  end

  def only_one_encouragement
    if Encouragement.exists?(user: current_user, achievement: @achievement)
      redirect_to achievement_path(@achievement), alert: "You already encouraged it. You can't be so generous!"
      return
    end
  end
end

i-rock/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

i-rock/app/helpers/application_helper.rb
module ApplicationHelper
end

i-rock/app/views/achievements/index.html.erb
<div><%= @achievements %></div>

i-rock/app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k, v| [k.split('_').first.capitalize, k]} ] %>
  <%= f.input :features, label: 'Featured Achievement' %>
  <%= f.input :cover_image, as: :file, label: 'Cover Image' %>
  <%= f.submit 'Create Achievement', class: 'btn btn-primary' %>
<% end %>

i-rock/app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<div>
  <%= @achievement.description_html.html_safe %>
</div>

<div class="encouragement">
  <h2>Encouragements <span id="encouragement-quantity"><%= @achievement.encouragements.count %></h2>
  <ul>
    <% @achievement.encouragements.each do |enc| %>
      <li>Encouragement left by <%= enc.user.email %>: <%= enc.message %></li>
    <% end %>
  </ul>
  <%= link_to 'Encouragement', new_achievement_encouragement_path(@achievement), id: 'encourage-button', class: 'btn btn-primary' %>
</div>

i-rock/app/views/encouragements/new.html.erb
<%= simple_form_for [@achievement, @encouragement] do |f| %>
  <%= f.input :message, placeholder: 'Say something nice...' %>
  <%= f.submit "Encourage", class: 'btn btn-primary' %>
<% end %>

i-rock/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IRock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to 'New Achievement', new_achievement_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

i-rock/app/views/welcome/index.html.erb
<h1>Welcome</h1>